# Generated by Django 5.2.4 on 2025-11-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
